"""
Django settings for whitemeat_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local .env file if one exists.
# This is a no-op in production (Render injects real env vars, and
# python-dotenv does NOT override variables that are already set), so
# the same settings file works locally and on Render unchanged.
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

# Allowed Hosts: ensure domain and subdomains are always allowed, combined with env var
default_hosts = [
    "whitemeatcompany.com",
    "www.whitemeatcompany.com",
    ".whitemeatcompany.com",
    ".onrender.com",
    "localhost",
    "127.0.0.1",
    "*",
]
env_hosts = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]
ALLOWED_HOSTS = list(dict.fromkeys(default_hosts + env_hosts))

# Trusted origins for CSRF protection over HTTPS
default_csrf = [
    "https://whitemeatcompany.com",
    "https://www.whitemeatcompany.com",
    "https://*.onrender.com",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
env_csrf = [origin.strip() for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if origin.strip()]
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(default_csrf + env_csrf))

# Tell Django to trust the X-Forwarded-Proto header from Render's reverse proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'frontend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'whitemeat_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'frontend.context_processors.site_settings',
                'frontend.context_processors.admin_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'whitemeat_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
import urllib.parse

database_url = os.environ.get("DATABASE_URL", "").strip()
DATABASES = None

if database_url:
    try:
        url = urllib.parse.urlparse(database_url)
        if url.scheme in ["postgres", "postgresql"]:
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': url.path[1:],
                    'USER': url.username or '',
                    'PASSWORD': url.password or '',
                    'HOST': url.hostname or '',
                    'PORT': url.port or '5432',
                    'CONN_MAX_AGE': 600,
                }
            }
        elif url.scheme == "mysql":
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.mysql',
                    'NAME': url.path[1:],
                    'USER': url.username or '',
                    'PASSWORD': url.password or '',
                    'HOST': url.hostname or '',
                    'PORT': url.port or '3306',
                }
            }
    except ValueError as e:
        # A malformed DATABASE_URL (e.g. the "[YOUR-PASSWORD]" placeholder
        # from Supabase's template pasted in unreplaced, which leaves
        # literal square brackets in the string) must NOT crash the whole
        # site at import time - fall through to SQLite below instead and
        # print a loud warning that shows up in the deploy logs.
        print(
            "!!! DATABASE_URL is malformed and could not be parsed "
            f"({e}). Falling back to SQLite. Fix DATABASE_URL on Render - "
            "check for an unreplaced [YOUR-PASSWORD] placeholder or "
            "unescaped special characters in the password. !!!"
        )

if DATABASES is None:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Supabase Storage Configuration

SUPABASE_URL = os.environ.get("SUPABASE_URL", "").strip()
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "").strip()

# Everything (menu photos, equipment/cage/breed/butchery images, hero
# slides, masterclass + order payment proofs) shares this ONE bucket.
# Each model's own `upload_to=` keeps files organised into folders within
# it (menu/, equipment/, hero/, order_proofs/2026/09/, ...).
# .strip() guards against stray whitespace/newlines pasted into Render's
# env var fields, which otherwise makes httpx blow up with a bare
# "Invalid URL" error that's hard to trace back to its cause.
SUPABASE_BUCKET_NAME = os.environ.get(
    "SUPABASE_BUCKET_NAME",
    "images"
).strip()

# Fallback for any file field that doesn't specify storage= explicitly
# (e.g. Notice image/document). MenuItem/Accessory/Cage/Breed/etc. use the
# get_*_storage() factories directly - see frontend/models.py.
# When Supabase isn't configured (no URL/KEY), everything - including these
# factories - falls back to local FileSystemStorage so uploads work in dev
# and only switch to Supabase once the env vars are set.
_supabase_ready = bool(SUPABASE_URL and SUPABASE_KEY)
STORAGES = {
    "default": (
        {
            "BACKEND": "whitemeat_backend.supabase_storage.SupabaseMediaStorage",
            "OPTIONS": {"bucket_name": SUPABASE_BUCKET_NAME},
        }
        if _supabase_ready
        else {"BACKEND": "django.core.files.storage.FileSystemStorage"}
    ),
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "https://whitemeatcompany.com",
    "https://www.whitemeatcompany.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_ALL_ORIGINS = True  # Only for development

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


import logging

# Logging configuration to show DEBUG logs in console
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        # Show DEBUG for your app
        'frontend': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# --- Self-ping logic for Render ---
import threading
import time
import requests

def _start_self_ping():
    def ping_self():
        app_url = os.getenv("APP_URL", "https://whitemeatcompany.com")  # Set APP_URL in Render env
        while True:
            try:
                requests.get(f"{app_url}/health/", timeout=10)
                print("Self-ping successful")
            except Exception as e:
                print(f"Self-ping failed: {e}")
            time.sleep(300)  # every 5 minutes
    threading.Thread(target=ping_self, daemon=True).start()

if os.getenv("RENDER", "False").lower() == "true":
    _start_self_ping()


