# Generated by Django 5.2.4 on 2025-07-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowDidYouHearAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('search_engine', 'Search Engine (Google, Bing)'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('friend', 'Friend or Colleague'), ('radio', 'Radio'), ('blog', 'Blog/Article'), ('ad', 'Online Advertisement'), ('other', 'Other')], max_length=32)),
                ('other_text', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
