# Generated by Django 5.2.4 on 2025-07-27 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_howdidyouhearaboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterclassEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Upcoming Masterclass', max_length=200)),
                ('date_range', models.CharField(help_text='e.g. August 2nd & 3rd, 2025', max_length=100)),
                ('fact', models.CharField(blank=True, max_length=255)),
                ('fact_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterclassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Day 1'), (2, 'Day 2')])),
                ('time', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='frontend.masterclassevent')),
            ],
            options={
                'ordering': ['day', 'time'],
            },
        ),
    ]
