# Generated by Django 5.2.4 on 2025-07-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_masterclassevent_masterclasssession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclassevent',
            name='fact',
        ),
        migrations.RemoveField(
            model_name='masterclassevent',
            name='fact_description',
        ),
    ]
