# Generated by Django 5.2.14 on 2026-08-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload accessory image', null=True, upload_to='equipment/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload menu item image', null=True, upload_to='menu/'),
        ),
    ]
