# Generated by Django 5.2.14 on 2026-08-24 12:38

import whitemeat_backend.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_accessory_image_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload accessory image', null=True, storage=whitemeat_backend.supabase_storage.get_equipment_storage, upload_to='equipment/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload menu item image', null=True, storage=whitemeat_backend.supabase_storage.get_menu_storage, upload_to='menu/'),
        ),
    ]
