# Generated by Django 5.2.14 on 2026-08-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_alter_accessory_image_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='image_filename',
            field=models.CharField(blank=True, help_text='Alternative: Image filename in static/images/', max_length=200),
        ),
    ]
