# Generated by Django 5.2.17 on 2026-09-03 11:20

import whitemeat_backend.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_accessory_image_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('subheading', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, help_text='Recommended 2400x1200px, < 400 KB.', null=True, storage=whitemeat_backend.supabase_storage.get_equipment_storage, upload_to='hero/')),
                ('background_image_filename', models.CharField(blank=True, help_text='Alternative: filename in static/images/ (e.g. home.jpeg).', max_length=200)),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('cta_primary_label', models.CharField(blank=True, max_length=40)),
                ('cta_primary_url', models.CharField(blank=True, max_length=300)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=40)),
                ('cta_secondary_url', models.CharField(blank=True, max_length=300)),
                ('overlay', models.CharField(choices=[('dark', 'Dark overlay (light text)'), ('light', 'Light overlay (dark text)'), ('none', 'No overlay')], default='dark', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(choices=[('equipment', 'Equipment / cage'), ('outgrower', 'Outgrower / handshake'), ('breeding', 'Breeding / rabbit'), ('masterclass', 'Masterclass / graduation'), ('restaurant', 'Restaurant / cutlery'), ('butchery', 'Butchery / cleaver'), ('shop', 'Shop / bag'), ('leaf', 'Leaf / health')], default='leaf', max_length=20)),
                ('url', models.CharField(help_text='Where the card links to, e.g. /equipment/ or a named path.', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='The White Meat Company', max_length=120)),
                ('tagline', models.CharField(blank=True, default="Pioneering Zimbabwe's white meat revolution.", max_length=160)),
                ('brand_slogan', models.CharField(default='EAT | LIVE | HEALTHY', help_text='Recurring brand philosophy shown in banners and dividers.', max_length=60)),
                ('whatsapp_number', models.CharField(default='263772333369', help_text='International format, digits only, no + (used for wa.me links).', max_length=20)),
                ('phone_primary', models.CharField(blank=True, default='+263 772 333 369', max_length=30)),
                ('phone_secondary', models.CharField(blank=True, default='+263 779 521 665', max_length=30)),
                ('email', models.EmailField(blank=True, default='rabbitholezim@gmail.com', max_length=254)),
                ('office_address', models.CharField(blank=True, default='17793 Tredgold Avenue, Belvedere, Harare', max_length=255)),
                ('restaurant_address', models.CharField(blank=True, default='Golden Quarry Road & Bulawayo Road, Harare', max_length=255)),
                ('business_hours', models.TextField(blank=True, default='Mon-Fri 08:00-17:00\nSat 08:00-15:00')),
                ('map_embed_url', models.URLField(blank=True, help_text="Google Maps 'embed' src URL for the footer/contact map.", max_length=1000)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/thewhitemeatco')),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True, default='https://x.com/WhiteMeatCompa1')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com/@brightt.makuchete2875')),
                ('tiktok_url', models.URLField(blank=True, default='https://www.tiktok.com/@thewhitemeatco')),
                ('whatsapp_channel_url', models.URLField(blank=True, default='https://whatsapp.com/channel/0029VaMwhvvEKyZDkNNk5H21')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
