# Generated by Django 5.2.17 on 2026-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_seed_home_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservicecard',
            name='icon',
            field=models.CharField(choices=[('breeding', 'Breeding stock (paw)'), ('equipment', 'Equipment (tools)'), ('masterclass', 'Masterclass (graduation cap)'), ('outgrower', 'Outgrower (handshake)'), ('restaurant', 'Rabbit Hole (utensils)'), ('butchery', 'Butchery (drumstick)'), ('shop', 'Shop (bag)'), ('leaf', 'Health (leaf)'), ('truck', 'Delivery (truck)'), ('phone', 'Contact (phone)')], default='leaf', max_length=20),
        ),
        migrations.AlterField(
            model_name='homeservicecard',
            name='url',
            field=models.CharField(help_text='Where the item links to, e.g. /equipment/ or a named path.', max_length=300),
        ),
    ]
