# Generated by Django 5.2.17 on 2026-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_reorder_service_cards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['page', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='heroslide',
            name='page',
            field=models.CharField(choices=[('home', 'Homepage'), ('equipment', 'Rabbit Farm Equipment'), ('breeding', 'Breeding Stock'), ('masterclass', 'Masterclass'), ('rabbithole', 'Rabbit Hole'), ('butchery', 'Whitemeat Butchery'), ('outgrowers', 'Outgrower Initiatives')], default='home', help_text="Which page's slider this slide belongs to.", max_length=20),
        ),
    ]
