# Generated by Django 5.2.17 on 2026-09-05 09:40

import whitemeat_backend.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_seed_equipment_slides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Auto-filled from the name if left blank.', unique=True)),
                ('tagline', models.CharField(blank=True, help_text="Short eyebrow, e.g. 'The gold standard of commercial rabbit farming'.", max_length=200)),
                ('description', models.TextField()),
                ('characteristics', models.TextField(blank=True, help_text="One characteristic per line, e.g. 'Mature weight: 4-5.5 kg'.")),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, help_text="Optional. Leave blank if stock isn't tracked.", null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload a breed photo.', null=True, storage=whitemeat_backend.supabase_storage.get_equipment_storage, upload_to='breeds/')),
                ('image_filename', models.CharField(blank=True, help_text='Alternative: filename in static/images/ (e.g. new.jpg).', max_length=200)),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
