# Generated by Django 5.2.17 on 2026-09-05 10:43

import django.db.models.deletion
import whitemeat_backend.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_seed_breeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclassevent',
            name='certification_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, help_text='Optional add-on certification fee. Leave blank to hide.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='masterclassevent',
            name='door_fee',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Extra late-registration fee for booking on the day, at the door.', max_digits=8),
        ),
        migrations.AddField(
            model_name='masterclassevent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=140, help_text='Standard course fee, per attendee.', max_digits=8),
        ),
        migrations.CreateModel(
            name='MasterclassDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to cancel/hide this date.')),
                ('location', models.CharField(blank=True, default='Belvedere, Harare', max_length=200)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(blank=True, help_text='Optional link back to the main event/schedule.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_dates', to='frontend.masterclassevent')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MasterclassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('attendees', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('payment_proof', models.FileField(blank=True, help_text='Screenshot/PDF of proof of payment.', null=True, storage=whitemeat_backend.supabase_storage.get_masterclass_storage, upload_to='masterclass_proofs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('proof_submitted', 'Payment Proof Submitted'), ('verified', 'Payment Verified'), ('rejected', 'Payment Rejected'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes, not shown to the customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('masterclass_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='frontend.masterclassdate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
