# Generated by Django 5.2.17 on 2026-09-05 13:57

import whitemeat_backend.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_seed_masterclass_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButcheryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('whole', 'Whole & half'), ('portions', 'Portions & cuts'), ('value', 'Value-added'), ('offal', 'Offal & extras'), ('bulk', 'Bulk & wholesale')], default='portions', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='each', help_text="e.g. 'each', 'per kg', '500g pack'.", max_length=40)),
                ('stock_note', models.CharField(blank=True, help_text="e.g. 'Fresh daily', 'Frozen', 'Pre-order only'.", max_length=60)),
                ('image', models.ImageField(blank=True, null=True, storage=whitemeat_backend.supabase_storage.get_equipment_storage, upload_to='butchery/')),
                ('image_filename', models.CharField(blank=True, help_text='Alternative: filename in static/images/.', max_length=200)),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
