# Generated by Django 5.2.17 on 2026-09-08 06:32

import whitemeat_backend.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_seed_butchery_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, help_text='Auto-filled from the name if left blank.', unique=True)),
                ('category', models.CharField(choices=[('breeders', 'Breeders'), ('weaners', 'Weaners'), ('growers', 'Growers'), ('complete', 'Complete system'), ('other', 'Other')], default='breeders', help_text='Shown as the tag on the product card.', max_length=20)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, help_text="One feature per line, e.g. '12 compartments: 1 buck + 11 does'.")),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacity', models.CharField(blank=True, help_text="e.g. 'Houses 1 buck + 11 does' or 'Up to 90 weaners'.", max_length=120)),
                ('image', models.ImageField(blank=True, help_text='Upload a cage photo.', null=True, storage=whitemeat_backend.supabase_storage.get_equipment_storage, upload_to='cages/')),
                ('image_filename', models.CharField(blank=True, help_text='Alternative: filename in static/images/ (e.g. cage3.jpg).', max_length=200)),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
