# Generated by Django 5.2.17 on 2026-09-11 08:09

import whitemeat_backend.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_seed_sheds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('cages', 'Cages'), ('sheds', 'Sheds'), ('accessories', 'Accessories'), ('breeding', 'Breeding Stock'), ('rabbithole', 'Rabbit Hole'), ('pagomo', 'Rabbit Hole Pagomo')], max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=30)),
                ('items_summary', models.TextField(help_text='Human-readable order lines, one per line.')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('proof', 'Paid - proof of payment attached'), ('cash', 'Pay in cash on collection/delivery')], default='cash', max_length=10)),
                ('proof_of_payment', models.FileField(blank=True, help_text='Screenshot/PDF of proof of payment. Required unless paying cash.', null=True, storage=whitemeat_backend.supabase_storage.get_order_storage, upload_to='order_proofs/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_bank_details',
            field=models.TextField(blank=True, help_text='Bank name, account name, account number, branch - shown to customers exactly as typed.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_ecocash_name',
            field=models.CharField(blank=True, help_text='Registered name on the EcoCash/mobile money account.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_ecocash_number',
            field=models.CharField(blank=True, help_text='EcoCash / mobile money number customers should pay to.', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text="Short note shown above the payment details, e.g. 'Pay 50% deposit to confirm your order.'"),
        ),
    ]
