# Generated by Django 5.2.17 on 2026-09-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_order_sitesettings_payment_bank_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('cages', 'Cages'), ('sheds', 'Sheds'), ('accessories', 'Accessories'), ('breeding', 'Breeding Stock'), ('butchery', 'Whitemeat Butchery'), ('rabbithole', 'Rabbit Hole'), ('pagomo', 'Rabbit Hole Pagomo')], max_length=20),
        ),
    ]
