# Generated by Django 5.2.17 on 2026-09-11 09:07

import whitemeat_backend.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_alter_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='background_video',
            field=models.FileField(blank=True, help_text='Optional: an MP4 that autoplays instead of the image above (the image is still used as the poster while it loads).', null=True, storage=whitemeat_backend.supabase_storage.get_equipment_storage, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='background_video_filename',
            field=models.CharField(blank=True, help_text='Alternative: filename in static/videos/ (e.g. but.mp4).', max_length=200),
        ),
    ]
