# Generated by Django 5.2.17 on 2026-09-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_set_home_rabbithole_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butcheryproduct',
            name='category',
            field=models.CharField(choices=[('fish', 'Fish'), ('chicken', 'Chicken'), ('rabbit', 'Rabbit Meat')], default='portions', max_length=20),
        ),
    ]
