# Generated by Django 5.2.17 on 2026-09-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0032_set_home_cages_masterclass_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('cages', 'Cages'), ('sheds', 'Sheds'), ('accessories', 'Accessories'), ('breeding', 'Breeding Stock'), ('butchery', 'Whitemeat Butchery'), ('rabbithole', 'Rabbit Hole'), ('pagomo', 'Rabbit Hole Pagomo'), ('mixed', 'Mixed cart')], max_length=20),
        ),
    ]
